use argon2::{
    Argon2, PasswordHash, PasswordHasher, PasswordVerifier,
    password_hash::{
        SaltString,
        rand_core::{OsRng, RngCore},
    },
};
use sha2::{Digest, Sha256};
use uuid::Uuid;

use crate::error::CryptoError;

pub fn hash_password(password: &str) -> Result<String, CryptoError> {
    let salt = SaltString::generate(&mut OsRng);

    let argon2 = Argon2::default();

    let hash = argon2
        .hash_password(password.as_bytes(), &salt)
        .map_err(|_| CryptoError::PasswordHash)?
        .to_string();

    Ok(hash)
}

pub fn verify_password(password: &str, hash: &str) -> Result<bool, CryptoError> {
    let parsed_hash = PasswordHash::new(hash).map_err(|_| CryptoError::PasswordVerify)?;

    let argon2 = Argon2::default();

    match argon2.verify_password(password.as_bytes(), &parsed_hash) {
        Ok(_) => Ok(true),
        Err(_) => Ok(false),
    }
}

pub fn generate_uuid() -> Uuid {
    Uuid::new_v4()
}

#[derive(Clone)]
pub struct GeneratedToken {
    pub raw: String,
    pub hash: String,
}

fn generate_raw_token() -> String {
    let mut bytes = [0u8; 32];
    OsRng.fill_bytes(&mut bytes);
    hex::encode(bytes)
}

pub fn generate_token() -> GeneratedToken {
    let raw = generate_raw_token();
    let hash = hash_secret(&raw);
    GeneratedToken { raw, hash }
}

/// Deterministic Sha256 hash without salt.
/// Used for randomly generated bytes only, not for passwords!
pub fn hash_secret(raw: &str) -> String {
    let mut hasher = Sha256::new();
    hasher.update(raw.as_bytes());
    hex::encode(hasher.finalize())
}

pub fn verify_token(raw: &str, hash: &str) -> bool {
    hash_secret(raw) == hash
}

pub struct GeneratedApiKey {
    pub full_key: String,
    pub prefix: String,
    pub hash: String,
}

pub fn generate_api_key(prefix: String) -> GeneratedApiKey {
    let secret = generate_raw_token();
    let full_key = format!("{}_{}", &prefix, secret);
    let hash = hash_secret(&full_key);

    GeneratedApiKey {
        full_key,
        prefix,
        hash,
    }
}
